### ISSUE TITLE
Configuration file is in the wrong place.

### ISSUE THREAD

**Issue by categoryik** [zhidao/milib-starter#1]
I got following message when I executed `./milib-install`.
```
./milib-install: line 12: ./config: No such file or directory
```
I found `config` file at the parent directory, it should be replaced.

**Comment by zhidao** [comment]
Actually, milib-install is supposed to run in the following style:
% scripts/milib-install
where `config` file is in the same directory with `scripts`.
Could you try this?

**Comment by zhidao** [comment]
I understand the problem is rather in README.md.

**Comment by zhidao** [comment]
I fixed README.md, also renamed milib-* to mi-lib-* for consistency with the group name.

**Comment by categoryik** [comment]
Thank you for your reply.
Your update has resolved the issue.
